hazelcast-client:
  serverIp: "hz-server"
  aws:
    enabled: false
    insideAwsEnvironment: false
    accessKey: ""
    secretKey: ""
    region: ""
    hostHeader: ""
    securityGroupName: ""
    tagKey: ""
    tagValue: ""